class GoogleDriveService {
  constructor() {
    this.initialized = false;
    this.clientId = import.meta.env.VITE_GOOGLE_CLIENT_ID;
    this.apiKey = import.meta.env.VITE_GOOGLE_API_KEY;
  }

  async initialize() {
    if (this.initialized) return;

    return new Promise((resolve, reject) => {
      // Check if gapi is already loaded
      if (window.gapi) {
        this.initializeGapi(resolve, reject);
        return;
      }

      // Load Google API client library
      const script = document.createElement('script');
      script.src = 'https://apis.google.com/js/api.js';
      script.onload = () => this.initializeGapi(resolve, reject);
      script.onerror = () => reject(new Error('Failed to load Google API script'));
      document.head.appendChild(script);
    });
  }

  async initializeGapi(resolve, reject) {
    try {
      await window.gapi.load('client:auth2', {
        callback: async () => {
          try {
            await window.gapi.client.init({
              apiKey: this.apiKey,
              clientId: this.clientId,
              discoveryDocs: ['https://www.googleapis.com/discovery/v1/apis/drive/v3/rest'],
              scope: 'https://www.googleapis.com/auth/drive.file'
            });
            
            this.initialized = true;
            console.log('Google API initialized successfully');
            resolve();
          } catch (error) {
            console.error('Google API init error:', error);
            reject(error);
          }
        },
        onerror: reject
      });
    } catch (error) {
      reject(error);
    }
  }

  async authenticate() {
    if (!this.initialized) {
      await this.initialize();
    }

    const auth = window.gapi.auth2.getAuthInstance();
    
    // Check if user is already signed in
    if (auth.isSignedIn.get()) {
      const user = auth.currentUser.get();
      const token = user.getAuthResponse().access_token;
      localStorage.setItem('google_drive_token', token);
      return token;
    }

    // Sign in the user
    try {
      const user = await auth.signIn();
      const token = user.getAuthResponse().access_token;
      localStorage.setItem('google_drive_token', token);
      return token;
    } catch (error) {
      if (error.error === 'popup_closed_by_user') {
        throw new Error('Sign-in was cancelled');
      }
      throw error;
    }
  }

  async ensureFolder() {
    const folderName = 'Patient Summaries';
    
    try {
      // Check if folder already exists
      const response = await window.gapi.client.drive.files.list({
        q: `name='${folderName}' and mimeType='application/vnd.google-apps.folder' and trashed=false`,
        fields: 'files(id, name)'
      });

      if (response.result.files.length > 0) {
        console.log('Folder already exists:', response.result.files[0].id);
        return response.result.files[0].id;
      }

      // Create new folder
      const folder = await window.gapi.client.drive.files.create({
        resource: {
          name: folderName,
          mimeType: 'application/vnd.google-apps.folder',
          description: 'Patient consultation summaries generated by Patient-Doctor Summarizer'
        },
        fields: 'id'
      });

      console.log('Created new folder:', folder.result.id);
      return folder.result.id;
    } catch (error) {
      console.error('Error ensuring folder:', error);
      throw new Error(`Failed to create folder: ${error.message}`);
    }
  }

  async uploadPDF(pdfBlob, fileName, summaryData) {
    try {
      const token = await this.authenticate();
      const folderId = await this.ensureFolder();

      // Create file metadata
      const metadata = {
        name: fileName,
        mimeType: 'application/pdf',
        parents: [folderId],
        description: `Medical summary for ${summaryData.patientName}`,
        properties: {
          patientName: summaryData.patientName,
          patientAge: summaryData.age,
          patientGender: summaryData.gender,
          diagnosis: summaryData.diagnosis,
          consultationDate: new Date().toISOString(),
          generatedBy: 'Patient-Doctor Summarizer'
        }
      };

      // Create form data for multipart upload
      const formData = new FormData();
      formData.append('metadata', new Blob([JSON.stringify(metadata)], { type: 'application/json' }));
      formData.append('file', pdfBlob);

      // Upload to Google Drive
      const response = await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,webViewLink,webContentLink', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`
        },
        body: formData
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(`Upload failed: ${errorData.error?.message || response.statusText}`);
      }

      const result = await response.json();
      console.log('File uploaded successfully:', result);
      return result;
    } catch (error) {
      console.error('Upload PDF error:', error);
      throw error;
    }
  }

  async generatePDF(summaryData) {
    // Create a professional-looking medical summary
    const pdfContent = `
MEDICAL CONSULTATION SUMMARY
Patient-Doctor Summarizer
Generated on: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}

================================================================================
PATIENT INFORMATION
================================================================================
Name: ${summaryData.patientName}
Age: ${summaryData.age}
Gender: ${summaryData.gender}

================================================================================
CHIEF COMPLAINT & SYMPTOMS
================================================================================
${summaryData.symptoms}

================================================================================
MEDICAL HISTORY
================================================================================
${summaryData.history || 'No significant medical history noted'}

================================================================================
EXAMINATION FINDINGS
================================================================================
${summaryData.examination || 'No examination findings recorded'}

================================================================================
DIAGNOSIS
================================================================================
${summaryData.diagnosis}

================================================================================
MEDICATION & TREATMENT
================================================================================
${summaryData.medication || 'No medication provided'}

================================================================================
FOLLOW-UP INSTRUCTIONS
================================================================================
${summaryData.followUp || 'No specific follow-up instructions'}

--------------------------------------------------------------------------------
This document was automatically generated by Patient-Doctor Summarizer.
Confidential medical information - For authorized personnel only.
--------------------------------------------------------------------------------
    `.trim();

    // Convert to blob (in a real app, you'd use a PDF library like jsPDF)
    return new Blob([pdfContent], { 
      type: 'application/pdf',
      endings: 'native'
    });
  }

  async uploadSummary(summaryData) {
    try {
      console.log('Starting Google Drive upload process...');
      
      // Validate required fields
      if (!summaryData.patientName || !summaryData.diagnosis) {
        throw new Error('Patient name and diagnosis are required');
      }

      // Generate PDF content
      const pdfBlob = await this.generatePDF(summaryData);
      
      // Create filename with timestamp
      const timestamp = new Date().toISOString().split('T')[0];
      const fileName = `Medical_Summary_${summaryData.patientName.replace(/\s+/g, '_')}_${timestamp}.pdf`;
      
      console.log('Uploading file:', fileName);
      
      // Upload to Google Drive
      const result = await this.uploadPDF(pdfBlob, fileName, summaryData);
      
      console.log('Upload successful:', result);
      
      return {
        success: true,
        driveLink: result.webViewLink,
        fileId: result.id,
        fileName: result.name,
        message: 'Summary successfully saved to Google Drive'
      };
    } catch (error) {
      console.error('Error in uploadSummary:', error);
      return {
        success: false,
        error: error.message,
        message: `Failed to upload to Google Drive: ${error.message}`
      };
    }
  }

  async listFiles() {
    try {
      await this.authenticate();
      
      const response = await window.gapi.client.drive.files.list({
        pageSize: 10,
        fields: 'files(id, name, webViewLink, createdTime)',
        orderBy: 'createdTime desc'
      });

      return response.result.files;
    } catch (error) {
      console.error('Error listing files:', error);
      throw error;
    }
  }

  isConnected() {
    const token = localStorage.getItem('google_drive_token');
    return !!(token && this.initialized);
  }

  disconnect() {
    localStorage.removeItem('google_drive_token');
    if (window.gapi && window.gapi.auth2) {
      const auth = window.gapi.auth2.getAuthInstance();
      if (auth) {
        auth.signOut();
      }
    }
    this.initialized = false;
    console.log('Disconnected from Google Drive');
  }

  // Test connection method
  async testConnection() {
    try {
      await this.initialize();
      const token = await this.authenticate();
      const folderId = await this.ensureFolder();
      
      return {
        success: true,
        message: 'Google Drive connection successful',
        folderId: folderId,
        hasToken: !!token
      };
    } catch (error) {
      return {
        success: false,
        message: `Connection test failed: ${error.message}`,
        error: error.message
      };
    }
  }
}

export default new GoogleDriveService();